from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet

import pandas as pd
import os
from datetime import datetime

# ==================================
# PDF FILE
# ==================================

pdf = SimpleDocTemplate(
    "SafetyEye_Report.pdf"
)

styles = getSampleStyleSheet()

content = []

# ==================================
# TITLE
# ==================================

content.append(
    Paragraph(
        "SafetyEye AI Monitoring Report",
        styles["Title"]
    )
)

content.append(
    Spacer(1,20)
)

# ==================================
# DATE
# ==================================

content.append(
    Paragraph(
        f"Generated On : {datetime.now()}",
        styles["Normal"]
    )
)

content.append(
    Spacer(1,10)
)

# ==================================
# ALERT DATA
# ==================================

alert_file = "alerts/alerts.csv"

if os.path.exists(alert_file):

    df = pd.read_csv(alert_file)

else:

    df = pd.DataFrame(
        columns=["Time","Alert"]
    )

total_violations = len(df)

# ==================================
# OCCUPANCY
# ==================================

occupancy = 0

if os.path.exists(
    "occupancy.txt"
):

    try:

        with open(
            "occupancy.txt",
            "r"
        ) as f:

            occupancy = int(
                f.read()
            )

    except:

        occupancy = 0

# ==================================
# SAFETY SCORE
# ==================================

safety_score = max(
    0,
    100 - (total_violations * 0.2)
)

# ==================================
# SUMMARY
# ==================================

content.append(
    Paragraph(
        f"Safety Score : {round(safety_score,2)}%",
        styles["Heading2"]
    )
)

content.append(
    Paragraph(
        f"Total Violations : {total_violations}",
        styles["Heading2"]
    )
)

content.append(
    Paragraph(
        f"Current Occupancy : {occupancy}",
        styles["Heading2"]
    )
)

content.append(
    Spacer(1,20)
)

# ==================================
# VIOLATION TABLE
# ==================================

content.append(
    Paragraph(
        "Recent Violations",
        styles["Heading1"]
    )
)

table_data = [
    ["Time","Alert"]
]

if not df.empty:

    for _, row in df.tail(10).iterrows():

        table_data.append(
            [
                str(row["Time"]),
                str(row["Alert"])
            ]
        )

else:

    table_data.append(
        [
            "No Records",
            "-"
        ]
    )

table = Table(
    table_data,
    colWidths=[200,250]
)

table.setStyle(
    TableStyle([
        (
            "BACKGROUND",
            (0,0),
            (-1,0),
            colors.orange
        ),
        (
            "TEXTCOLOR",
            (0,0),
            (-1,0),
            colors.white
        ),
        (
            "GRID",
            (0,0),
            (-1,-1),
            1,
            colors.black
        ),
        (
            "FONTNAME",
            (0,0),
            (-1,0),
            "Helvetica-Bold"
        )
    ])
)

content.append(table)

content.append(
    Spacer(1,20)
)

# ==================================
# FOOTER
# ==================================

content.append(
    Paragraph(
        "Generated by SafetyEye AI Monitoring System",
        styles["Italic"]
    )
)

# ==================================
# BUILD PDF
# ==================================

pdf.build(content)

print(
    "✅ SafetyEye_Report.pdf Generated Successfully"
)